version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - cd sam-hello
      - sam package --template-file template.yaml --s3-bucket  --output-template-file packaged-template.yaml --s3-bucket $SAM_BUCKET
      - cp packaged-template.yaml ../packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml